# http://wiki.ros.org/navfn
GlobalPlanner:
  lethal_cost:                  100   #default: 253
  neutral_cost:                 50    #default: 50
  cost_factor:                  3.0   #default: 3.0
  orientation_mode:             1     #default: 1-Forward
  publish_potential:            false #default: false

EBandPlannerROS:
  differential_drive: false
  max_acceleration: 2.5
  max_vel_lin: 0.5
  max_vel_th: 1.0
  min_vel_lin: 0.0
  min_vel_th: 0.0
  xy_goal_tolerance: 0.02
  yaw_goal_tolerance: 0.01
