#Machine Configuration
x_vel_limit_mps:                      1.0
y_vel_limit_mps:                      0.35
accel_limit_mps2:                     0.5
decel_limit_mps2:                     2.5
dtz_decel_limit_mps2:                 2.5
yaw_rate_limit_rps:                   1.0
yaw_accel_limit_rps2:                 3.5
wheel_diameter_m:                     0.1524
wheel_base_length_m:                  0.50173
wheel_track_width_m:                  0.538100
gear_ratio:                           5.0
motion_while_charging:                0
motion_ctl_input_filter:              0

#Correction factors
strafe_correction_factor:             0.0
yaw_correction_factor:                0.0

#teleop parameters
teleop_x_vel_limit_mps:               0.5
teleop_y_vel_limit_mps:               0.5
teleop_yaw_rate_limit_rps:            1.0
teleop_accel_limit_mps2:              1.0
teleop_yaw_accel_limit_rps2:          2.0
jog_velocity_mps:                     0.1
jog_yaw_rate_rps:                     0.2
