# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           base_link
transform_tolerance:        0.5

# ---footprint (Meters):---
footprint: [[0.37,0.28], [0.37,-0.28], [-0.37,-0.28], [-0.37,0.28]]
footprint_padding: 0.01

#robot_radius:               0.622

### Costmap definitions ###
update_frequency: 5.0
publish_frequency: 5.0
obstacle_layer/footprint_clearing_enabled: true
plugins:                     []

static:
  unknown_cost_value:        -1
  lethal_cost_threshold:     150
  map_topic:                 map
  subscribe_to_updates:      true
  
obstacles_costmap2d:
    observation_sources: vector_scan
    vector_scan: {topic:                   /vector/base_scan_filtered,
                  data_type:               LaserScan,
                  expected_update_rate:    0.2,
                  observation_persistence: 0.0,
                  marking:                 true,
                  clearing:                true,
                  inf_is_valid:            true,
                  min_obstacle_height:     -0.1,
                  max_obstacle_height:     2.0,
                  obstacle_range:          4.75,
                  raytrace_range:          8.0}

inflation:
  inflation_radius:           0.7  #default 0.5
  cost_scaling_factor:        10.0 #default 10.0


